server.port=8080
spring.application.name=AgentScope-test

# OpenAI 配置
agentscope.openai.api-key=sk-5df11b3db1fd42c99b93f87cf728xx
agentscope.openai.base-url=https://dashscope.aliyuncs.com/compatible-mode/v1
agentscope.openai.model-name=qwen-plus

# AnalyticDB PostgreSQL 向量库配置
agentscope.analyticdb.host=gp-2ze3od1xx-master.gpdb.rds.aliyuncs.com
agentscope.analyticdb.port=5432
agentscope.analyticdb.database=knowledgebase
agentscope.analyticdb.username=product_doc_test
agentscope.analyticdb.password=TEST_xxx
agentscope.analyticdb.table-name=document_xx
agentscope.analyticdb.vector-dimension=1536
agentscope.analyticdb.top-k=3
agentscope.analyticdb.score-threshold=0.5
agentscope.analyticdb.enable-hybrid-search=false

# 阿里云 AnalyticDB Embedding 配置
agentscope.analyticdb.access-key-id=LTAI5tBta3PKxASdYxxx
agentscope.analyticdb.access-key-secret=jZKKSrodx406Rxxxx
agentscope.analyticdb.db-instance-id=gp-2ze3odxxx
agentscope.analyticdb.region-id=cn-beijing
agentscope.analyticdb.embedding-model=text-embedding-v4
agentscope.analyticdb.embedding-dimension=1536
agentscope.analyticdb.endpoint=gpdb.aliyuncs.com

# 阿里云 AnalyticDB Rerank 配置
agentscope.analyticdb.rerank-model=qwen3-rerank
agentscope.analyticdb.rerank-top-k=5
agentscope.analyticdb.enable-rerank=true
agentscope.analyticdb.rerank-candidate-count=20
